language: c

branches:
  only:
    - stable   #. stable (public) release
    - frozen   #. freeze point between stable and unstable
    - volatile #. short-lived but promising branches worth testing
    - unstable #. don't expect no history-rewrites here!

before_install:
  - sudo apt-get update -qq
  - share/unit/travis before_install

env:
  global:
    - SITE_PROFILE="TRAVIS"
    - PATH="${PATH}:${HOME}/bin"
  matrix:
    - CONTEXT=installer MODULE=-
    - CONTEXT=execute MODULE=net   #. nima/site#7
    - CONTEXT=execute MODULE=hgd   #. nima/site#3
    - CONTEXT=execute MODULE=gpg   #. nima/site#5
    - CONTEXT=execute MODULE=util  #. nima/site#4
    - CONTEXT=execute MODULE=vault #. nima/site#17
    - CONTEXT=execute MODULE=git   #. nima/site#9

script:
  - share/unit/travis script
